Models/Algorithm.cs
namespace GPOSite.Models
{
    public class Algorithm
    { 
        public string OEIS_ID { get; set; }
        public string Information { get; set; } 
        public int Number { get; set; }
        public bool Empty
        {
            get
            {
                return (string.IsNullOrWhiteSpace(OEIS_ID) &&
                          string.IsNullOrWhiteSpace(Information) &&
                          Number == 0);
            }
        }
    }
}

Models/ErrorViewModel.cs
namespace GPOSite.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Response.cs
namespace GPOSite.Models
{
    public class Response
    {
        public List<Algorithm>? algInfo {  get; set; }
        public string? response { get; set; }
    }
}

Models/User.cs
namespace GPOSite.Models
{
    public class User
    {
        public int Id { get; set; }
        public string Username { get; set; }

    }
}

Controllers/AlgController.cs
using Dapper;
using GPOSite.Algorithms;
using GPOSite.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Data;

namespace GPOSite.Controllers
{
    public class AlgController : Controller
    {
        private readonly ILogger<AlgController> _logger;
        private readonly IConfiguration _config;
        public readonly Response resp = new Response();
        public AlgController(ILogger<AlgController> logger, IConfiguration config)
        {
            _logger = logger;

            _config = config;
        }

        public IDbConnection Connection
        {
            get
            {
                return new SqlConnection(_config.GetConnectionString("DefaultConnection"));
            }
        }

        private List<Algorithm> SearchByOEIS(string queryText)
        {
            using (IDbConnection db = Connection)
            {
                var result = db.Query<Algorithm>($"SELECT Information,Number FROM OEISInfo WHERE OEIS_ID = '{queryText}'").ToList();

                return result;
            }

        }

        public IActionResult IndexAlg()
        {

            return View();
        }

        public IActionResult SearchAlg(string search, string? n, string? m, string? k)
        {

            if (n == null & m == null & k == null & search != null)
            {
                var model = SearchByOEIS(search);
               
                return View("IndexAlg", model);
            }
            else if(search != null & n != null)
            {
                var model = SearchByOEIS(search);
                UseAlg(n);
                return View("IndexAlg", model);
            }
            else if(search != null & n != null & m != null)
            {
                var model = SearchByOEIS(search);
                return View("IndexAlg", model);
            }
            else if (search != null & n != null & m!= null & k != null)
            {
                var model = SearchByOEIS(search);
                return View("IndexAlg", model);
            }
            else
            {
                var model = SearchByOEIS(search);
                return View("IndexAlg", model);
            }
           
        }

        public void UseAlg(string n)
        {
            var Alg = new A000045();
            int n1 = Int32.Parse(n);
            ViewData["Response"] = Alg.Start(n1);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using GPOSite.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Diagnostics;
using Microsoft.Data.SqlClient;
using Dapper;
using GPOSite.Algorithms;
using System.Net;

namespace GPOSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Alg/IndexAlg.cshtml
@{
    ViewData["Title"] = "Поиск алгоритмов";
    var response = ViewData["Response"] as List<string>;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Поиск алгоритмов</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&family=Open+Sans:wght@500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/normalizer.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styleAlg.css" asp-append-version="true" />
</head>
<body>
    @using (@Html.BeginForm("SearchAlg", "Alg", FormMethod.Get))
                {
    <header class="header">
        <div class="header_logo">
            <a href="#">
                <img src="~/logo.svg" alt="">
            </a>
        </div>
        <div class="header_container">
            <nav class="header_navigation">
                <a href="#">| Главная</a>
            </nav>
            <div class="header_search">
                
                    @Html.TextBox("search","", htmlAttributes: new {@placeholder = "Введите номер из OEIS"})
                    <button type="submit">Найти</button>
                
            </div>
            
           @*  <div class="header_search">
                <form action="">
                    <input placeholder="Введите номер из OEIS">
                    <button type="submit">Найти</button>
                </form>
            </div> *@
        </div>
    </header>
    <main class="main">
        <div class="main_obj-descritption">
            @if (@Model != null)
            {
                @foreach (var item in @Model)
                {
                    <div>

                        <h1>@item.Information</h1>

                    </div>
                }
            }
            @* <h1>Числа фибоначчи - элементы числовой последовательности в которой первые два числа равны нулю и единице, а каждое последующее число равно сумме двух предыдущих чисел</h1> *@
        </div>
        <div class="main_chng-container">
            <div class="main_obj-chng">
                <a>ВЫБОР ОБЪЕКТА</a>
                <input class="main_input-chng">
            </div>
        </div>
        <div class="main_gen-container">
            <div class="main_gen-href">
                <div class="main_gen">
                    <a>ГЕНЕРАЦИЯ ОБЪЕКТА</a>
                    <div class="main_gen-start">
                        
                        <div class="main_gen-params">
                            @if (@Model != null)
                            {
                                @foreach (var item in @Model)
                                {
                                    @if (@item.Number == 1)
                                    {
                                          <a>N=</a>
                                            @Html.TextBox("n","", htmlAttributes: new {@class="main_gen-params-input"})


                                            @* <a>N=</a> <input class="main_gen-params-input"> *@
                                        }
                                        else if (@item.Number == 2)
                                        {
                                            <a>N=</a> <input class="main_gen-params-input"> <a>M=</a> <input class="main_gen-params-input">
                                        }
                                        else if (@item.Number == 3)
                                        {
                                            <a>N=</a> <input class="main_gen-params-input"> <a>M=</a> <input class="main_gen-params-input">  <a>K=</a> <input class="main_gen-params-input">
                                        }
                                        else
                                        {
                                            <a>N=</a> <input class="main_gen-params-input">
                                        }
                                    }
                                }
                                            else if (@Model == null)
                                {
                                    <a>N=</a> <input class="main_gen-params-input">
                                }
                                </div>
                                <button type="submit" class="main_gen-btn"><a>Выполнить</a></button>
                        
                        </div>

                    <div class="main_gen-result">
                            @if (@response != null)
                            {
                                @for (int i = 0; i < @response.Count; i++)
                                {
                                    @response[i]
                                }
                            }
                    </div>
                </div>
                <div class="main_href">
                    <a>ССЫЛКИ</a>
                    <a href="https://youtu.be/MThhnNVncnY?si=IpKHegTIQ5gfUkS5&t=3">ПРИМЕР ССЫЛКА</a>
                </div>
            </div>
            <div class="main_alg-dsrc-container">
                <div class="main_alg-dsrc">
                    <a>ОПИСАНИЕ АЛГОРИТМА</a>
                    @if (@Model != null)
                    {
                        @foreach (var item in @Model)
                        {
                            <div>

                                @item.Information

                            </div>
                        }
                    }
                </div>
                <div class="main_alg-formulas">
                    <a>ФОРМУЛЫ</a>
                </div>
                <div class="main_alg-I-ILI">
                    <a>Генерация и/или</a>
                </div>
                <div class="main_alg-psevdo">
                    <a>Псевдик</a>
                </div>
            </div>

        </div>
       
    </main>
    }
</body>
</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Главная страница";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная страница</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&family=Open+Sans:wght@500;600;700;800&display=swap" rel="stylesheet">
    @* <link rel="stylesheet" href="normalizer.css"> *@
    <link rel="stylesheet" href="~/css/normalizer.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styleHome.css" asp-append-version="true" />
</head>
<body>
    <header class="header">
        <div class="header_logo">
            <a href="#">
                <img src="logo.svg" alt="">
            </a>
        </div>
        <div class="header_container">
            <nav class="header_navigation">
                <a asp-area="" asp-controller="Alg" asp-action="IndexAlg">| Главная страница</a>
                @* <a href="alg">| Главная страница</a> *@
            </nav>
            @* <div class="header_search">
                <form action="">
                    <input placeholder="Введите номер из OEIS">
                    <button type="submit">Найти</button>
                </form>
            </div> *@
        </div>
    </header>
    <main class="main">
        <div class="main_text">
            <h1>Данный сайт - проект, который представляет из себя онлайн энциклопедию, содержащая систематизированную информацию о существующих алгоритмах комбинаторной генерации, их свойства и имеющихся ограничениях применения</h1>
        </div>
        <div class="main_container">
            <div class="main_list">
                <img src="list.svg" alt="">
                <a>СПИСОК</a>
            </div>
            <div class="main_signup">
                <a>Авторизация</a>
                <h3>Логин</h3>
                <input class="main_signup-input">
                <h3>Пароль</h3>
                <input class="main_signup-input">
                <button type="submit" class="main_reg-btn">Я новенький</button>
                <button type="submit" class="main_guest-btn">Я уже смешарик</button>
            </div>
        </div>
    </main>
</body>
</html>

Views/List/IndexList.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="styleLIST.css">
    <title>Список</title>
</head>
<body>
    <img src="images/logo.ico">
    <b>|</b>
    <a href="index.html">Главная</a>
    <div class="blue-bar">Список</div>
    <div class="gray-blockchangeBIG">
        <b>Список алгоритмов?</b>
        <br>
        <div class="rectangle">
            <br><a href="https://youtu.be/HLQ1cK9Edhc?si=9T0DvUZ0QPm3nuOd&t=16" class="button-link">Тык</a>
        </div>

    </div>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GPO</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    @* <link rel="stylesheet" href="~/css/styleHome.css" asp-append-version="true" /> *@

</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>  
    @await RenderSectionAsync("Scripts", required: false)
   
</body>
</html>